services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123

  backend:
    build: .
    container_name: backend
    ports:
      - "8085:8085"
    depends_on:
      - mongodb
    environment:
      # Aqui a string de conexão pro Mongo dentro do docker-compose (use o nome do serviço)
      MONGO_URI: mongodb://admin:senha123@mongodb:27017/todo?authSource=admin
    command: npm run start

volumes:
  mongodb_data:
