version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: senha123

  backend:
    build: .
    container_name: backend
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://admin:senha123@mongodb:27017/todo?authSource=admin
    command: npm run start
    networks:
      - internal_network

volumes:
  mongodb_data:

networks:
  internal_network:
    external: true
