version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - internal_network
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: backend
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://mongodb:27017"  # conexão sem usuário e senha
    command: npm run start
    networks:
      - internal_network

networks:
  internal_network:
    external: true
